site_name: Wiki
site_url: https://berkan-dogan.github.io/wiki
docs_dir: src
repo_url: https://github.com/berkan-dogan/wiki
repo_name: berkan-dogan/wiki
use_directory_urls: false

plugins:
  - social:
      cards_layout_options:
        logo: assets/logo.png
  - search
  - offline

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  icon:
    logo: simple/linux
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.prune
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  language: tr
  palette:
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Açık moda geç
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Koyu moda geç

nav:
  - Anasayfa: index.md
  - Dil Modeli Rehberleri: p.md
  - Veri İşleme: z.md
  - Geleneksel Modeller: y.md
  - Yeni Akademik Çalışmalar: x.md
  - LinuxTurkey Arşivi:
      - Anasayfa: lt/index.md
      - Sık Sorulan Sorular: lt/rehberler/sss.md
      - Kullanıcı Rehberleri:
          - lt/rehberler/linux_uyumlu_donanim.md
          - lt/rehberler/lenovo_bios.md
          - lt/rehberler/fedora-nvidia-akmod-rehberi.md
          - lt/rehberler/fedora-yukseltme-rehberi.md
          - lt/rehberler/plymouth.md
      - Güvenlik ve Sistem:
          - lt/rehberler/firefox-hardened.md
          - lt/rehberler/flatpak-ve-tarayicilar.md
          - lt/rehberler/verified-boot.md
      - Editör Rehberleri:
          - lt/rehberler/hangi_dagitim.md
          - lt/rehberler/immutable-dagitimlar.md
          - lt/rehberler/windowstan_linuxa.md
      - Faydalı Bağlantılar: lt/faydali_baglantilar.md
      - Diğer Wiki Kaynakları:
          - Nix Öğreniyoruz: https://linuxturkey.github.io/nix-ogreniyoruz/

